version: '3.4'

services:
  iot-hub-backend:
    image: ${DOCKER_REGISTRY-}iothubbackend
    build:
      context: .
      dockerfile: iot-hub-backend/Dockerfile

  messageprocessing:
    image: ${DOCKER_REGISTRY-}messageprocessing
    build:
      context: .
      dockerfile: MessageProcessing/Dockerfile

  rabbitmq:
    build:
      context: .
      dockerfile: RabbitMQ/Dockerfile