version: '3.4'

services:
  iot-hub-backend:
    container_name: "ASP.Net-Backend"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=https://+:443;http://+:80;
    ports:
      - "80"
      - 5000:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  messageprocessing:
    container_name: "MessageProcessing"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  postgresql:
    container_name: "PostgreSQL"
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./Dockerfiles/PostgreSQL/pgsql-dump.sql:/docker-entrypoint-initdb.d/pgsql-dump.sql

  mqttserver:
    container_name: "MQTTServer"
    ports:
      - 1883:1883
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  influxdb:
    container_name: "InfluxDB"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      # - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=cliconfigname
    ports:
      - 8086:8086
    volumes:
      - ./Dockerfiles/InfluxDB/influxdb2/:/var/lib/influxdb2
      - ./Dockerfiles/InfluxDB/Scripts/BucketCreateScript.sh:/docker-entrypoint-initdb.d/BucketCreateScript.sh
